name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIARYQJ6K5ULTUEFHFD
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test:headless

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/report-gen s3://reportgen-bucket
